exec_param:
  threads: 0 # if 0 - uses the maximum number of threads - 1
  max_iter: 100  # number of iterations (repetitions/batches) - must be more than batch_iter todo - fix this in outside code
  batch_size: 20 # number of iterations per batch - must be less than max_iter
  plot_curves: True
  plot_surf: True
  plot_hist: True
  backup_data: True
  output_type: 'complete'  # complete or simple or raw

roi_param:
  grid: True
  grid_lines: 1000
  grid_columns: 1000
  cel_size: 30
  map: False
  name_map: ''

macel_param:
  ue_dist_typ: 'gaussian'  # options: 'gaussian' or 'uniform' sampling
  n_samples: 200  # number of samples per distribution
  # ==================================== if the distribution sampling is GAUSSIAN ====================================
  n_centers: 4  # number of distributions to be summed (gaussian/etc) --> samples per dist = n_samples * n_centers
  center_distribution: 'cluster' # 'uniform' or 'cluster' for the  centers distribution
  # ===================================================================================================
  time_slots: 1000  # number of time slots (1 ms)
  time_slot_lngt: 1  # duration of a time slot (ms)
  uplink: True  # if True: simulates downlink comm.
  downlink: True  # if True: simulates uplink comm.
  min_bs: 1  # minimum number of BSs to be simulated
  max_bs: 30  # maximum number of BSs to be simulated
  mux_tdd_up_time: 0  # percentage (between 0 and 1) of time used for the uplink when using TDD

downlink_scheduler:  # scheduler specifications for the downlink side
  criteria: 30  # Mbps
  scheduler_typ: 'prop-smp'  # RR (round-robin), prop-cmp (proposed complete), prop-smp (p roposed simplified) or BCQI (Best Channel Quality Indicator)
  bw_slot: 10  # slot fixed bandwidth for scheduler with a queue (RR)
  t_min: 10  # minimum allocated time for an execution time = time_slots

uplink_scheduler:  # scheduler specifications for the uplink side
  criteria: 10  # Mbps
  scheduler_typ: 'RR'  # RR (round-robin), prop-cmp (proposed complete), prop-smp (proposed simplified) or BCQI (Best Channel Quality Indicator)
  bw_slot: 10  # slot fixed bandwidth for scheduler with a queue (RR)
  t_min: 10  # minimum allocated time for an execution time = time_slots

antenna_param:  # -- refer to ITU 2101 --
  # antenna element parameters
  max_element_gain: 5
  phi_3db: 65
  theta_3db: 65
  front_back_h: 30
  sla_v: 30
  # antenna array parameters
  frequency: 10  # not used
  n_rows: 8
  n_columns: 8
  horizontal_spacing: 0.5
  vertical_spacing: 0.5

bs_param:
  freq: 3.5  # frequency (GHz)
  htx: 30
  tx_power: 20  # transmission power (dBW)
  bw: 300  # bw for n sectors (to be fixed)
  n_sectors: 3
  gain: 10  # not used
  downtilt: 0
  n_beams: 10

ue_param:
  hrx: 1.5
  tx_power: -3 # dBW
